## Create a `metadata` dataframe for Food Mama project:

In [1]:
import pandas as pd
import mama
import os
import matplotlib.pyplot as plt
%matplotlib inline

### Loading the Datasets into Pandas dataframe

In [2]:
path = "datasets/"
files = os.listdir(path)

dfs = []
for file in files:
    filename = file.split("_")
    dfs.append(filename[0])
    exec(dfs[-1] + '= pd.read_csv(path + file)')

print("Name of the dataframes created: ", *dfs, sep="\n")

Name of the dataframes created:
food
item
recipe

In [3]:
recipe.head()

,id,title,servings,ingredients,instructions,created_at,updated_at,recommendable,status,origin,link,rating
0,9,"Salade mâche, jambon de Bayonne, mozzarella",4,4 bonne poignée de mâche \r\n40 tomate cerise ...,"Après avoir coupé en dés la mozzarella, couper...",2017-12-14 14:56:37.166524,2018-10-05 09:16:42.390163,NaN,dismissed,www.marmiton.org,http://www.marmiton.org/recettes/recette_salad...,limit
1,10,Ciabattina al pesto,1,Ciabattina\r\nJambon de Parme\r\nTomates confi...,Ouvrir le pain Ciabattina en deux et tartiner ...,2017-12-14 14:56:46.270433,2018-10-05 09:16:42.45289,NaN,dismissed,www.club-sandwich.net,http://www.club-sandwich.net/mobile/fiche.php?...,limit
2,402,Tortilla aux champignons et salade,4,250 g de champignons de Paris\r\r\n4 oeufs\r\r...,Préchauffer le four à 180 °C (th. 6).\r\nCoupe...,2017-12-15 16:41:37.056079,2018-10-05 09:16:42.505825,NaN,dismissed,www.mangerbouger.fr,http://www.mangerbouger.fr/Manger-Mieux/Recett...,limit
3,2,Steak haché et pâtes,1,2.0 filets huile d'olive\r\n1.0 steak haché\...,"Dans une casserole, portez à ébullition un gra...",2017-12-13 16:17:24.125137,2018-10-05 09:16:42.55582,NaN,dismissed,www.wecook.fr,https://www.wecook.fr/recette/steak-hache-et-p...,good
4,4,Beef Bagel,1,Pain Bagel\r\nCarpaccio de boeuf\r\nFromage fr...,Placer les tranches de carpaccio dans un plat ...,2017-12-13 17:13:29.069001,2018-10-05 09:16:42.597349,NaN,dismissed,www.club-sandwich.net,http://www.club-sandwich.net/mobile/fiche.php?...,limit

### Run `preprocessing` module to modify and to clean the dataframes (drop unnecessary columns, rename columns, replace index with "id", fill the missing data, and change data type).

In [4]:
dataframes = [food, item, recipe]
foods, items, recipes = mama.preprocessing(dataframes)
items.head()

,recipe-ingredient,name_food,title_recipe,ingredients_recipe,origin_recipe
id,,,,,
1,2.0 filets huile d'olive,huile d'olive,Steak haché et pâtes,2.0 filets huile d'olive\r\n1.0 steak haché\...,www.wecook.fr
2,1.0 steak haché,steak haché,Steak haché et pâtes,2.0 filets huile d'olive\r\n1.0 steak haché\...,www.wecook.fr
3,70.0 grammes pâtes,pâtes,Steak haché et pâtes,2.0 filets huile d'olive\r\n1.0 steak haché\...,www.wecook.fr
4,500 g de semoule moyenne,semoule,Taboulé ultra-facile,500 g de semoule moyenne \r\n500 g de tomate e...,www.marmiton.org
5,500 g de tomate environ (ébouillantées pour ot...,tomate,Taboulé ultra-facile,500 g de semoule moyenne \r\n500 g de tomate e...,www.marmiton.org

### Merging tables to create a meta_data table

In [5]:
merge_table = pd.merge(recipes, items, left_on='title', right_on='title_recipe')
merge_table = merge_table.loc[:, ['recipe_id', 'title', 'servings', 'origin', 'rating', 'name_food']]
merge_table.head(10)

,recipe_id,title,servings,origin,rating,name_food
0,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,mâche
1,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,tomate cerise
2,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,mozzarella
3,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,jambon cru
4,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,croutons
5,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,vinaigrette
6,10,Ciabattina al pesto,1,www.club-sandwich.net,limit,pain ciabattina
7,10,Ciabattina al pesto,1,www.club-sandwich.net,limit,jambon de Parme
8,10,Ciabattina al pesto,1,www.club-sandwich.net,limit,tomate confite
9,10,Ciabattina al pesto,1,www.club-sandwich.net,limit,pesto

In [6]:
meta_data = pd.merge(merge_table, foods, left_on='name_food', right_on='name')
meta_data.head(10)

,recipe_id,title,servings,origin,rating,name_food,food_id,name,availability,category_id,ancestry
0,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,limit,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
1,566,Sandwich Spécial Magy,1,www.club-sandwich.net,limit,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
2,397,Salade de ravioles,2,www.mangerbouger.fr,good,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
3,508,Sandwich Marcilhacy's,1,www.club-sandwich.net,limit,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
4,564,Sandwich Rösti Burger,1,www.club-sandwich.net,limit,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
5,391,Salade fraîcheur,4,www.mangerbouger.fr,good,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
6,1213,"Haricots rouges, maïs, tomate, champignon, mâc...",1,clementale_,good,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
7,1113,"Saumon fumé, avocat, mâche, riz, vinaigrette, ...",1,mama,good,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
8,476,Parmentier de canard et salade verte,6,www.mangerbouger.fr,limit,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86
9,551,Bruschetta Mâche/Parmesan,1,www.club-sandwich.net,good,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86

### Convert string features to nominal categorical variables

- Approach #1 - Find and Replace

In [7]:
rating_cat = {"rating": {"avoid": 1, "limit": 2, "good": 3, "excellent": 4, "unknown": 0}}
meta_data.replace(rating_cat, inplace=True)

- Approach #2 - Label Encoding

In [8]:
meta_data.availability = meta_data.availability.astype('category')
meta_data["availability_cat"] = meta_data.availability.cat.codes

- Approach #3 - Use Scikit-Learn

In [9]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
meta_data["origin_id"] = lb_make.fit_transform(meta_data["origin"])

### Convert *string* to an integer *list* in `availability` column

In [10]:
#list = [int(s) for s in meta_data.availability for s in s.replace(',','').split(" ")]
meta_data["availability_lst"] = [[int(s) for s in s.replace(',','').split(" ")] for s in meta_data.availability]
meta_data.head()

,recipe_id,title,servings,origin,rating,name_food,food_id,name,availability,category_id,ancestry,availability_cat,origin_id,availability_lst
0,9,"Salade mâche, jambon de Bayonne, mozzarella",4,www.marmiton.org,2,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86,0,70,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]"
1,566,Sandwich Spécial Magy,1,www.club-sandwich.net,2,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86,0,67,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]"
2,397,Salade de ravioles,2,www.mangerbouger.fr,3,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86,0,69,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]"
3,508,Sandwich Marcilhacy's,1,www.club-sandwich.net,2,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86,0,67,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]"
4,564,Sandwich Rösti Burger,1,www.club-sandwich.net,2,mâche,42,mâche,"01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12",14,86,0,67,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]"

### Preparing a dataframe `cluster_data` for Unsupervised learning models

- Remove seasoning ingredients by their category_ids (sauces, épices, sel, sucres, beurre, jus, alcools, levure, eau).

In [11]:
seasoning_categories = [18, 34, 37, 38, 39, 41, 42, 44, 45]
cluster_data = meta_data[meta_data['category_id'].apply(lambda x: x not in seasoning_categories)]

- Rearrange dataframe columns

In [12]:
cluster_data = cluster_data.loc[:, ['title','recipe_id','origin_id','servings','rating','food_id','category_id','availability_lst','ancestry']]
cluster_data.rename(columns={'title':'recipe_title', 'food_id':'ingredient_id', 'category_id':'ingredient_cat'}, inplace=True)
cluster_data.head(10)

,recipe_title,recipe_id,origin_id,servings,rating,ingredient_id,ingredient_cat,availability_lst,ancestry
0,"Salade mâche, jambon de Bayonne, mozzarella",9,70,4,2,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
1,Sandwich Spécial Magy,566,67,1,2,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
2,Salade de ravioles,397,69,2,3,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
3,Sandwich Marcilhacy's,508,67,1,2,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
4,Sandwich Rösti Burger,564,67,1,2,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
5,Salade fraîcheur,391,69,4,3,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
6,"Haricots rouges, maïs, tomate, champignon, mâc...",1213,10,1,3,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
7,"Saumon fumé, avocat, mâche, riz, vinaigrette, ...",1113,42,1,3,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
8,Parmentier de canard et salade verte,476,69,6,2,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86
9,Bruschetta Mâche/Parmesan,551,67,1,3,42,14,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]",86

In [13]:
cluster_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6106 entries, 0 to 8463
Data columns (total 9 columns):
recipe_title        6106 non-null object
recipe_id           6106 non-null int64
origin_id           6106 non-null int64
servings            6106 non-null int64
rating              6106 non-null int64
ingredient_id       6106 non-null int64
ingredient_cat      6106 non-null int64
availability_lst    6106 non-null object
ancestry            6106 non-null int64
dtypes: int64(7), object(2)
memory usage: 477.0+ KB

In [14]:
cluster_data.describe()

,recipe_id,origin_id,servings,rating,ingredient_id,ingredient_cat,ancestry
count,6106.000000,6106.000000,6106.000000,6106.000000,6106.000000,6106.000000,6106.000000
mean,662.750246,54.661317,1.914019,2.547003,114.581068,20.985752,46.575827
std,356.721204,16.073162,1.478863,0.819601,132.960621,8.028326,124.018508
min,2.000000,0.000000,1.000000,0.000000,1.000000,11.000000,0.000000
25%,370.000000,42.000000,1.000000,2.000000,19.500000,14.000000,0.000000
50%,672.000000,61.000000,1.000000,2.000000,64.000000,17.000000,1.000000
75%,986.000000,69.000000,4.000000,3.000000,161.000000,27.000000,1.000000
max,1243.000000,73.000000,8.000000,4.000000,597.000000,47.000000,519.000000